
// ═══════════════════════════════════════════════════════════════════════════
// DOMINIO · Marketplace de estilos (dirección creativa envasada)
// Un estilo define TODO el criterio estético: paleta, óptica, luz, grade,
// ritmo, música, tipografía, transiciones y tono verbal. Cambiar de estilo
// regenera la campaña entera de forma coherente.
// ═══════════════════════════════════════════════════════════════════════════

const STYLES = [
  {
    id: 'premium-cinematic', name: 'Premium Cinematic', emoji: '🥃',
    tagline: 'Lujo contenido, silencio, materia noble.',
    keywords: ['premium', 'lujo', 'elegante', 'exclusivo', 'cinematografico', 'sofisticado', 'alta gama', 'refinado'],
    palette: { primary: '#0B0B0D', secondary: '#C9A227', accent: '#E8E4DC', dark: '#000000', light: '#F5F2EC' },
    lighting: ['chiaroscuro', 'rim', 'volumetric'], grades: ['noir', 'kodak'],
    lenses: ['85mm', '100mm-macro', 'anamorphic'], moves: ['slow-push', 'orbit', 'rack-focus'],
    shots: ['macro', 'hero', 'close', 'insert'], fx: ['particles', 'smoke', 'lens-flare'],
    transitions: ['dissolve', 'fadeblack', 'smoothleft'],
    pacing: { avgShotSec: 3.2, cutsPerMin: 19, energy: 2 },
    music: { genre: 'orchestral cinematic', bpm: 72, mood: 'contenida, solemne, con crescendo final',
      instruments: ['cuerdas graves', 'piano preparado', 'coro sutil', 'sub bass'] },
    typography: { display: 'Serif de alto contraste (Didot / Playfair)', body: 'Grotesca neutra (Inter / Helvetica Now)', tracking: 'amplio' },
    voice: { tone: 'grave, pausado, con autoridad', pace: 0.86, style: 'narrador de marca' },
    tone: 'sobrio, aspiracional, sin superlativos baratos',
    filmStock: 'Kodak Vision3 500T', era: 'contemporáneo atemporal',
    negative: ['plástico', 'saturación excesiva', 'stock photo', 'tipografía comic', 'ruido visual'],
    refs: ['Apple product films', 'campañas de relojería suiza', 'Villeneuve para publicidad'],
  },
  {
    id: 'epic-sport', name: 'Épico Deportivo', emoji: '🔥',
    tagline: 'Sudor, impacto, superación. El cuerpo como épica.',
    keywords: ['epico', 'deportivo', 'deportistas', 'atleta', 'potente', 'energia', 'fuerza', 'entrenamiento', 'gym', 'rendimiento'],
    palette: { primary: '#111418', secondary: '#FF3B1F', accent: '#F2F4F7', dark: '#05070A', light: '#FFFFFF' },
    lighting: ['hard-key', 'rim', 'strobe'], grades: ['bleach', 'teal-orange'],
    lenses: ['24mm', '35mm', '135mm'], moves: ['handheld', 'whip-pan', 'fpv', 'tracking'],
    shots: ['close', 'medium', 'extreme-close', 'wide'], fx: ['slow-motion', 'speed-ramp', 'sparks', 'motion-blur'],
    transitions: ['cut', 'zoomin', 'wipeleft'],
    pacing: { avgShotSec: 1.4, cutsPerMin: 43, energy: 5 },
    music: { genre: 'trailer híbrido / drums & bass', bpm: 148, mood: 'brutal, ascendente, con drop',
      instruments: ['taikos', 'braams', 'sintetizador distorsionado', 'palmas'] },
    typography: { display: 'Sans condensada extra bold (Druk / Anton)', body: 'Sans geométrica bold', tracking: 'cerrado' },
    voice: { tone: 'intenso, entrecortado, cercano al micrófono', pace: 1.08, style: 'monólogo interior' },
    tone: 'directo, imperativo, sin adornos',
    filmStock: 'digital ARRI, alto ISO', era: 'ahora',
    negative: ['poses sonrientes de stock', 'gimnasio vacío iluminado plano', 'cámara lenta sin motivo'],
    refs: ['Nike "Winner Stays"', 'Under Armour "Rule Yourself"', 'campañas de crossfit'],
  },
  {
    id: 'nordic-minimal', name: 'Minimal Nórdico', emoji: '🕊️',
    tagline: 'Aire, luz difusa y una sola idea por plano.',
    keywords: ['minimal', 'minimalista', 'limpio', 'nordico', 'simple', 'clean', 'esencial', 'calma', 'zen'],
    palette: { primary: '#F7F5F2', secondary: '#2B2B2B', accent: '#A9B7A5', dark: '#1A1A1A', light: '#FFFFFF' },
    lighting: ['overcast', 'softbox', 'gradient'], grades: ['pastel', 'clean'],
    lenses: ['50mm', '85mm', '35mm'], moves: ['static', 'slow-push', 'parallax'],
    shots: ['top', 'insert', 'medium', 'close'], fx: ['none', 'particles'],
    transitions: ['fade', 'dissolve', 'smoothleft'],
    pacing: { avgShotSec: 4.0, cutsPerMin: 15, energy: 1 },
    music: { genre: 'ambient minimal', bpm: 84, mood: 'serena, cálida, casi silencio',
      instruments: ['piano con fieltro', 'pads', 'vinilo suave'] },
    typography: { display: 'Grotesca neutra light (Söhne / Neue Haas)', body: 'La misma familia en regular', tracking: 'normal' },
    voice: { tone: 'suave, cercano, susurrado', pace: 0.9, style: 'confidencia' },
    tone: 'honesto, breve, sin marketing',
    filmStock: 'Fuji Pro 400H', era: 'contemporáneo escandinavo',
    negative: ['fondos recargados', 'colores saturados', 'texto sobre texto', 'sombras duras'],
    refs: ['Muji', 'Aesop', 'catálogos de diseño danés'],
  },
  {
    id: 'street-energy', name: 'Street Energy', emoji: '🛹',
    tagline: 'Cultura urbana, cámara viva, imperfección deliberada.',
    keywords: ['urbano', 'street', 'joven', 'callejero', 'viral', 'ugc', 'gen z', 'tiktok', 'fresco', 'divertido'],
    palette: { primary: '#151515', secondary: '#D8FF3E', accent: '#FF4FD8', dark: '#0A0A0A', light: '#FAFAFA' },
    lighting: ['neon', 'hard-key', 'golden'], grades: ['cyberpunk', 'clean'],
    lenses: ['14mm', '24mm', '35mm'], moves: ['handheld', 'whip-pan', 'snorricam'],
    shots: ['pov', 'medium-close', 'wide', 'close'], fx: ['speed-ramp', 'light-streaks', 'freeze'],
    transitions: ['cut', 'pixelize', 'slideup', 'zoomin'],
    pacing: { avgShotSec: 1.1, cutsPerMin: 54, energy: 5 },
    music: { genre: 'hip hop / hyperpop', bpm: 132, mood: 'juguetona, con bajo dominante',
      instruments: ['808', 'hi-hats rápidos', 'sample vocal cortado'] },
    typography: { display: 'Sans display con outline (Monument Extended)', body: 'Sans bold', tracking: 'cerrado' },
    voice: { tone: 'natural, hablado, sin locución impostada', pace: 1.12, style: 'testimonial a cámara' },
    tone: 'coloquial, con humor, tuteo',
    filmStock: 'iPhone + grano añadido', era: 'ahora mismo',
    negative: ['aspecto corporativo', 'locución de radio', 'stock photo sonriente'],
    refs: ['campañas de Liquid Death', 'Duolingo social', 'skate videos'],
  },
  {
    id: 'tech-future', name: 'Tech Futurista', emoji: '⚡',
    tagline: 'Precisión, datos e ingeniería como espectáculo.',
    keywords: ['tecnologia', 'tech', 'futurista', 'innovacion', 'digital', 'software', 'saas', 'ia', 'gadget', 'moderno'],
    palette: { primary: '#05070E', secondary: '#19ACB1', accent: '#7B61FF', dark: '#000208', light: '#E9F6F7' },
    lighting: ['gradient', 'rim', 'volumetric'], grades: ['cyberpunk', 'clean'],
    lenses: ['100mm-macro', 'probe', '50mm'], moves: ['orbit', 'slow-push', 'parallax'],
    shots: ['macro', 'insert', 'hero', 'top'], fx: ['explode-view', 'light-streaks', 'morph'],
    transitions: ['smoothleft', 'circleopen', 'dissolve'],
    pacing: { avgShotSec: 2.4, cutsPerMin: 25, energy: 3 },
    music: { genre: 'synth cinematic', bpm: 110, mood: 'precisa, en construcción',
      instruments: ['arpegio analógico', 'sub pulsante', 'foley digital'] },
    typography: { display: 'Sans técnica (Space Grotesk / Suisse Intl Mono)', body: 'Sans neutra', tracking: 'normal' },
    voice: { tone: 'claro, articulado, sin dramatismo', pace: 1.0, style: 'explicativo' },
    tone: 'preciso, con cifras, sin hipérbole',
    filmStock: 'digital limpio, sin grano', era: 'próxima década',
    negative: ['personas mirando pantallas genéricas', 'hologramas azules cliché', 'circuitos de stock'],
    refs: ['keynotes de producto', 'Rimac / Tesla films', 'Framer / Linear'],
  },
  {
    id: 'gourmet-macro', name: 'Gourmet Macro', emoji: '🍯',
    tagline: 'Textura comestible: el apetito entra por el detalle.',
    keywords: ['comida', 'alimento', 'bebida', 'gourmet', 'sabor', 'restaurante', 'cafe', 'delicioso', 'receta'],
    palette: { primary: '#2A1B12', secondary: '#E0803A', accent: '#F6E7CE', dark: '#150C07', light: '#FFF8EF' },
    lighting: ['hard-key', 'rim', 'golden'], grades: ['kodak', 'earth'],
    lenses: ['100mm-macro', 'probe', '85mm'], moves: ['slow-push', 'orbit', 'rack-focus'],
    shots: ['macro', 'extreme-close', 'top', 'insert'], fx: ['slow-motion', 'splash', 'smoke', 'condensation'],
    transitions: ['dissolve', 'fade', 'smoothleft'],
    pacing: { avgShotSec: 2.2, cutsPerMin: 27, energy: 3 },
    music: { genre: 'acústico cálido', bpm: 96, mood: 'apetitosa, con foley protagonista',
      instruments: ['guitarra nylon', 'percusión de manos', 'foley de cocina'] },
    typography: { display: 'Serif humanista (Recoleta)', body: 'Sans redondeada', tracking: 'normal' },
    voice: { tone: 'cálido, apetitoso, con pausas', pace: 0.92, style: 'sensorial' },
    tone: 'sensorial, con verbos de textura',
    filmStock: 'Kodak Gold 200', era: 'artesanal contemporáneo',
    negative: ['comida fría de plástico', 'iluminación cenital plana', 'platos desordenados'],
    refs: ['Chef\'s Table', 'campañas de Häagen-Dazs', 'foodfilm de alta velocidad'],
  },
  {
    id: 'editorial-fashion', name: 'Editorial Fashion', emoji: '👗',
    tagline: 'Actitud, silueta y composición de portada.',
    keywords: ['moda', 'ropa', 'fashion', 'estilo', 'editorial', 'belleza', 'pasarela', 'coleccion', 'diseno'],
    palette: { primary: '#F2EFEA', secondary: '#111111', accent: '#B23A48', dark: '#0D0D0D', light: '#FFFFFF' },
    lighting: ['strobe', 'rembrandt', 'gradient'], grades: ['mono', 'pastel'],
    lenses: ['85mm', '135mm', '50mm'], moves: ['static', 'whip-pan', 'tracking'],
    shots: ['full', 'medium', 'close', 'cowboy'], fx: ['freeze', 'motion-blur', 'light-streaks'],
    transitions: ['cut', 'wipeleft', 'fadewhite'],
    pacing: { avgShotSec: 1.8, cutsPerMin: 33, energy: 4 },
    music: { genre: 'electrónica minimal de pasarela', bpm: 124, mood: 'fría, rítmica, repetitiva',
      instruments: ['caja seca', 'bajo sintético', 'texturas metálicas'] },
    typography: { display: 'Serif editorial extra light en caja alta', body: 'Grotesca fina', tracking: 'muy amplio' },
    voice: { tone: 'neutro, casi ausente; el silencio manda', pace: 0.95, style: 'mínimo' },
    tone: 'aforístico, pocas palabras',
    filmStock: 'Ilford HP5 push', era: 'referencia noventas',
    negative: ['sonrisas comerciales', 'fondos con logotipos', 'poses de catálogo'],
    refs: ['editoriales de Vogue Italia', 'campañas Jacquemus', 'Helmut Lang archive'],
  },
  {
    id: 'warm-lifestyle', name: 'Lifestyle Cálido', emoji: '🏡',
    tagline: 'Gente real, casas reales, luz de ventana.',
    keywords: ['hogar', 'familia', 'lifestyle', 'natural', 'cotidiano', 'bienestar', 'salud', 'bebe', 'mascota', 'cercano'],
    palette: { primary: '#FBF6F0', secondary: '#8C6A4E', accent: '#7FA36B', dark: '#2C241E', light: '#FFFFFF' },
    lighting: ['overcast', 'golden', 'softbox'], grades: ['kodak', 'earth'],
    lenses: ['35mm', '50mm', '85mm'], moves: ['handheld', 'slow-push', 'parallax'],
    shots: ['medium', 'close', 'wide', 'insert'], fx: ['particles', 'none'],
    transitions: ['dissolve', 'fade', 'smoothleft'],
    pacing: { avgShotSec: 3.0, cutsPerMin: 20, energy: 2 },
    music: { genre: 'folk acústico', bpm: 92, mood: 'luminosa, sin pretensión',
      instruments: ['guitarra acústica', 'ukelele', 'silbido', 'palmas suaves'] },
    typography: { display: 'Serif suave (Tiempos)', body: 'Sans humanista', tracking: 'normal' },
    voice: { tone: 'cercano, natural, con sonrisa audible', pace: 0.98, style: 'conversacional' },
    tone: 'cálido, en segunda persona, sin tecnicismos',
    filmStock: 'Kodak Portra 400', era: 'presente doméstico',
    negative: ['casas de catálogo sin usar', 'actores demasiado perfectos', 'luz artificial fría'],
    refs: ['campañas de IKEA', 'Airbnb films', 'documental doméstico'],
  },
  {
    id: 'retro-90s', name: 'Retro 90s', emoji: '📼',
    tagline: 'VHS, saturación y nostalgia deliberada.',
    keywords: ['retro', 'vintage', 'noventa', 'nostalgia', 'analogico', 'vhs', 'clasico', 'antiguo'],
    palette: { primary: '#1B1035', secondary: '#FF6B6B', accent: '#4ECDC4', dark: '#0E0820', light: '#FFE66D' },
    lighting: ['neon', 'hard-key', 'gradient'], grades: ['cyberpunk', 'clean'],
    lenses: ['24mm', '35mm', '50mm'], moves: ['static', 'whip-pan', 'crane-up'],
    shots: ['medium', 'wide', 'close', 'hero'], fx: ['light-streaks', 'freeze', 'morph'],
    transitions: ['wipeleft', 'pixelize', 'circleopen'],
    pacing: { avgShotSec: 2.0, cutsPerMin: 30, energy: 4 },
    music: { genre: 'synthwave', bpm: 118, mood: 'nostálgica y brillante',
      instruments: ['sintetizador FM', 'caja con reverb larga', 'bajo slap'] },
    typography: { display: 'Sans geométrica con sombra dura', body: 'Sans bold', tracking: 'amplio' },
    voice: { tone: 'entusiasta, casi de teletienda pero con ironía', pace: 1.05, style: 'presentador' },
    tone: 'divertido, exagerado con guiño',
    filmStock: 'VHS con aberración cromática', era: '1994',
    negative: ['aspecto moderno y limpio', 'tipografía actual', 'grading neutro'],
    refs: ['spots de los noventa', 'Stranger Things', 'MTV bumpers'],
  },
  {
    id: 'luxury-noir', name: 'Luxury Noir', emoji: '🖤',
    tagline: 'Deseo, sombra y una sola fuente de luz.',
    keywords: ['noir', 'oscuro', 'misterio', 'perfume', 'joyeria', 'seduccion', 'nocturno', 'exclusivo', 'deseo'],
    palette: { primary: '#000000', secondary: '#8E7B45', accent: '#C0C0C0', dark: '#000000', light: '#D9D4CA' },
    lighting: ['chiaroscuro', 'rim', 'neon'], grades: ['noir', 'mono'],
    lenses: ['85mm', 'anamorphic', '135mm'], moves: ['slow-push', 'orbit', 'rack-focus'],
    shots: ['extreme-close', 'close', 'hero', 'profile'], fx: ['smoke', 'particles', 'lens-flare'],
    transitions: ['fadeblack', 'dissolve', 'cut'],
    pacing: { avgShotSec: 2.6, cutsPerMin: 23, energy: 3 },
    music: { genre: 'trip hop oscuro', bpm: 88, mood: 'magnética, con silencios',
      instruments: ['contrabajo', 'vocal etérea', 'percusión con reverb'] },
    typography: { display: 'Serif condensada en caja alta', body: 'Grotesca fina', tracking: 'muy amplio' },
    voice: { tone: 'susurrado, íntimo, muy cerca del micrófono', pace: 0.82, style: 'seductor' },
    tone: 'evocador, elíptico, casi poético',
    filmStock: 'Cinestill 800T', era: 'noche eterna',
    negative: ['luz plana', 'fondo blanco', 'explicaciones largas', 'colores cálidos brillantes'],
    refs: ['campañas de fragancias', 'Dior films', 'Wong Kar-wai'],
  },
];

const styleById = (id) => STYLES.find((x) => x.id === id) || STYLES[0];

/** Objetivos de campaña (definen el funnel y el peso de cada mensaje). */
const OBJECTIVES = [
  { id: 'awareness', label: 'Notoriedad', kpi: 'CPM / alcance / VTR', weight: { hook: 3, proof: 1, offer: 1 } },
  { id: 'consideration', label: 'Consideración', kpi: 'CTR / tiempo de visionado', weight: { hook: 2, proof: 3, offer: 2 } },
  { id: 'conversion', label: 'Conversión', kpi: 'ROAS / CPA / CVR', weight: { hook: 2, proof: 2, offer: 3 } },
  { id: 'launch', label: 'Lanzamiento', kpi: 'alcance + CVR de preventa', weight: { hook: 3, proof: 2, offer: 2 } },
  { id: 'remarketing', label: 'Remarketing', kpi: 'ROAS / frecuencia', weight: { hook: 1, proof: 3, offer: 3 } },
];
const objectiveById = (id) => OBJECTIVES.find((x) => x.id === id) || OBJECTIVES[0];
